/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from 'next'

import './globals.css'
import KakaoScript from './KakaoScript/page'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

declare global {
  interface Window {
    Kakao: any
    naver: any
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body
        suppressHydrationWarning
        className='m-0 flex h-dvh items-center justify-center bg-[#ffffff]'
      >
        <div className='relative flex h-full min-h-screen w-full max-w-414 flex-col bg-purple-20'>
          {children}
        </div>
        <KakaoScript />
        <Script
          src='https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.2.js'
          strategy='beforeInteractive'
        />
      </body>
    </html>
  )
}
