import type { Metadata } from 'next'

import './globals.css'
import KakaoScript from './KakaoScript/page'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

declare global {
  interface Window {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Kakao: any
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body className='bg-[#7A4AFF]'>{children}</body>
      <KakaoScript />
    </html>
  )
}
