#!/bin/sh

echo "🚀 pre-push 훅 실행됨"
echo "Remote: $1"
echo "URL: $2"

FORBIDDEN_HTTPS_URL="https://github.com/potenday-06/front-end.git" # 레포 https url 
FORBIDDEN_SSH_URL="git@github.com:potenday-06/front-end.git" # 레포 ssh url
FORBIDDEN_REF_MAIN="main"
FORBIDDEN_REF_DEV="develop"

# 현재 브랜치 가져오기
current_branch=$(git rev-parse --abbrev-ref HEAD)
echo "현재 푸쉬하는 브랜치: $current_branch"

if [ "$current_branch" = "$FORBIDDEN_REF_MAIN" ] || [ "$current_branch" = "$FORBIDDEN_REF_DEV" ]; then
    echo "🚫 MAIN OR DEVELOP 브랜치로 직접 PUSH 할 수 없습니다! 🚫"
    exit 1
fi

echo "✅ Push 허용됨"
exit 0